# Generated by Django 4.2.3 on 2023-08-11 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Last_Name', models.CharField(max_length=200)),
                ('First_Name', models.CharField(max_length=200)),
                ('Username', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='users')),
                ('Password1', models.DateTimeField(auto_now_add=True)),
                ('Password2', models.ImageField(blank=True, null=True, upload_to='users')),
                ('Email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
